#########################################
# ___  ___       ______  _         _    #
# |  \/  |       | ___ \| |       | |   #
# | .  . | _   _ | |_/ /| |  ___  | |_  #
# | |\/| || | | ||  __/ | | / _ \ | __| #
# | |  | || |_| || |    | || (_) || |_  #
# \_|  |_/ \__, |\_|    |_| \___/  \__| #
#           __/ |                       #
#          |___/                        #
#########################################

# The language that should be used in MyPlot
# Available languages: eng, nld, vie, spa, chs, zho, deu, cze, tur, kor, fre, tgl
#
# English language pack by @jasonwynn10
# Dutch language pack by @Wies
# Vietnamese language pack by @daany123
# Spanish language pack by @thelucyclub
# Chinese ( ROC ) pack by @jerryzooyoyo
# Chinese ( PRC ) pack by @jerryzooyoyo
# German language pack by @morpheusTP and @SalmonGER
# Czech language pack by @GamakCZ
# Turkish language pack by @Eren5960
# Korean language pack by @Johnmacrocraft
# French language pack by @ad5001
# Tagalog language pack by @Lentou
Language: eng

# Allows editing language file as a config
# This is not recommended unless you have a good text editor!
Custom Messages: false

# The data provider where plot data is stored.
# Current providers are: sqlite, mysql, json, and yaml.
DataProvider: sqlite

# contains settings for mysql provider to use when selected
MySQLSettings:
  Host: 127.0.0.1
  Port: 3306
  Username: default
  Password: password
  DatabaseName: MyPlot
  ShutdownOnFailure: false

# Use an economy with MyPlot. This will allow for plot pricing such as claiming, clearing, etc.
# Currently supported economy plugins: Economy$, PocketMoney, EssentialsPE, EconomyPlus
# Be sure not to use more than 1 economy plugin!
UseEconomy: false

# Amount of plots to be cached.
# Increasing this number will improve performance, but also increase memory usage.
PlotCacheSize: 256

# When a player enters a plot, a popup with basic info will be shown
ShowPlotPopup: true

# If WorldStyler is installed, MyPlot will use that to clear the entire plot at once
FastClearing: false

# Amount of blocks to reset per tick. This only applies if FastClearing is disabled
# Increasing this number will speed up '/p clear' and '/p reset' but also increases lag
ClearBlocksPerTick: 256

# These settings will be used when creating a new world with the default generator.
DefaultWorld:

  # Restrict entities (e.g. tnt) from moving except falling
  # This will prevent things like tnt cannons from ruining other plots
  RestrictEntityMovement: true

  # Restrict battles between players in plot worlds
  # This setting overrides the settings of individual plots on world generation
  RestrictPVP: false

  # Update liquids (e.g. Water) from updating and moving
  # This will allow things like water to lag the server in plot worlds
  UpdatePlotLiquids: false

  # Edit Border Blocks (Any block immediately adjacent to a plot space)
  # This will allow players to break and place their own border blocks
  EditBorderBlocks: true

  # How much it costs to claim a plot (Economy must be set to 'true')
  ClaimPrice: 0
  # How much it costs to clear a plot (Economy must be set to 'true')
  ClearPrice: 0
  # How much it costs to dispose a plot (Economy must be set to 'true')
  DisposePrice: 0
  # How much it costs to reset a plot (Economy must be set to 'true')
  ResetPrice: 0
  # How much it costs to clone a plot (Economy must be set to 'true')
  ClonePrice: 0

  # The size of a plot
  PlotSize: 32
  # The height of a plot
  GroundHeight: 64
  # The width of the road
  RoadWidth: 7

  # The block that the road is made of (Default is Oak Planks)
  RoadBlock: '5:0'
  # The block that plot walls are made of (Default is Stone Slabs)
  WallBlock: '44:0'
  # The block used as the plot floor (Default is Grass)
  PlotFloorBlock: '2:0'
  # The block that fills the rest of the plot (Default is Dirt)
  PlotFillBlock: '3:0'
  # The block at the bottom (Default is Bedrock)
  BottomBlock: '7:0'