MaxPlotsPerPlayer: 5
DataProvider: 'sqlite'
UseEconomy: false

DefaultWorld:
  MaxPlotsPerPlayer: 5
  ClaimPrice: 0
  ClearPrice: 0
  DisposePrice: 0
  ResetPrice: 0
  RoadBlock: '5'
  RoadWidth: 7
  WallBlock: '44'
  PlotFloorBlock: '2'
  PlotFillBlock: '3'
  PlotSize: 22
  GroundHeight: 64
  BottomBlock: '7'
